#'''Command-line usage resource config.'''#


# --- sample_rule --- #

sample_rule_threads: 10
sample_rule_mem_mb: 100000


# --- first_rule --- #

first_rule_threads: 5
first_rule_mem_mb: 20000


# --- second_rule --- #

python_rule_threads: 20
python_rule_mem_mb: 80000

